@startuml FitnessApp

left to right direction

package com.groupfive.fitness  {
    Class MainActivity
    Class MyApp
    Class TrainingNotificationService

    package exercise  {
        Enum ComparisonType
        Class ExerciseAngleConstraint
        Interface ExerciseDetector
        Class ExerciseDetectorFactory
        Interface ExercisePoseConstraint
        Class ExercisePoseConstraints
        Class SquatExerciseDetector
        Class SitUpExerciseDetector
        Class PushUpExerciseDetector
        Enum WorkoutType
    }

    package model {
        package plannedworkout {
            package repository {
                Class FirebasePlannedWorkoutRepository
                Interface PlannedWorkoutRepository
                Class TestPlannedWorkoutRepository
            }

            Class PlannedWorkoutSession
        }

        package user {
            package repository as user-repository  {
                Interface UserRepository
                Class FirebaseUserRepository
            }
            Class User
        }

        package workout {
            package repository as workout-repository {
                Interface WorkoutSessionRepository
                Class FirebaseWorkoutSessionRepository
            }
            Class WorkoutSession
        }
    }

    package screens {
        package calendar {
            Class CalendarFragment
            Class CalendarViewModel
            Class DayViewContainer
            Class MonthViewContainer
        }

        package exercisecamera {
            Class ExerciseCameraFragment
            Class ExerciseCameraViewModel
            Class PoseView
        }

        package Exercise {
            Class ExerciseFragment
            Class WorkoutTypeAdapter
        }

        package profile {
            class ProfileFragment
        }

        package startupscreen {
            Class LoginFragment
            Class RegisterFragment
        }

        package stats {
            Class ExerciseStatsAdapter
            Class StatsFragment
            Class StatsViewModel
        }

        package workoutday  {
            Class PlannedWorkoutSessionAdapter
            Class WorkoutDayFragment
            Class WorkoutDayViewModel
            Class SetupPlannedExerciseFragment
            Class SetupPlannedExerciseViewModel
            Class WorkoutSessionsAdapter
        }
    }

    package util {
        Class CalendarUtils
        Class PoseUtils
    }
}

' Exercise system
ExerciseDetector <|-- SquatExerciseDetector
ExerciseDetector <|-- SitUpExerciseDetector
ExerciseDetector <|-- PushUpExerciseDetector

ComparisonType <-- ExerciseAngleConstraint
ExercisePoseConstraint <|-- ExerciseAngleConstraint
ExercisePoseConstraint o-- ExercisePoseConstraints

ExercisePoseConstraints o-- SquatExerciseDetector
ExercisePoseConstraints o-- SitUpExerciseDetector
ExercisePoseConstraints o-- PushUpExerciseDetector

ExerciseAngleConstraint o-- SquatExerciseDetector
ExerciseAngleConstraint o-- SitUpExerciseDetector
ExerciseAngleConstraint o-- PushUpExerciseDetector

SquatExerciseDetector <-- ExerciseDetectorFactory
SitUpExerciseDetector <-- ExerciseDetectorFactory
PushUpExerciseDetector <-- ExerciseDetectorFactory
PushUpExerciseDetector <-- ExerciseDetectorFactory

' Model
' PlannedWorkout
PlannedWorkoutRepository <|-- TestPlannedWorkoutRepository
PlannedWorkoutRepository <|-- FirebasePlannedWorkoutRepository
PlannedWorkoutSession o-- PlannedWorkoutRepository
TrainingNotificationService o-- MyApp

' User
User o-- UserRepository
UserRepository <|-- FirebaseUserRepository

' Workout
WorkoutSession o-- WorkoutSessionRepository
WorkoutSessionRepository <|-- FirebaseWorkoutSessionRepository

' Screens
' ExerciseCamera
ExerciseCameraFragment o-- ExerciseDetector
ExerciseCameraFragment o-- ExerciseCameraViewModel
WorkoutSessionRepository <-- ExerciseCameraViewModel
PoseView o-- ExerciseCameraFragment

' Calendar
PlannedWorkoutRepository o-- CalendarViewModel
DayViewContainer o-- CalendarFragment
MonthViewContainer o-- CalendarFragment
CalendarViewModel o-- CalendarFragment

' WorkoutDay
PlannedWorkoutRepository o-- WorkoutDayViewModel
WorkoutDayViewModel o-- WorkoutDayFragment
PlannedWorkoutSessionAdapter o-- WorkoutDayFragment
SetupPlannedExerciseViewModel o-- SetupPlannedExerciseFragment

' Profile
UserRepository o-- ProfileFragment

' Exercise
WorkoutTypeAdapter o-- ExerciseFragment

' Stats
StatsViewModel o-- StatsFragment
WorkoutSessionRepository <-- StatsViewModel
ExerciseStatsAdapter o-- StatsFragment

@enduml