name: Android CI - Test, Build Gradle, Build Project and Build & Upload APK

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run JUnit Tests
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create file
      run: cat /home/runner/work/fitnessapp/fitnessapp/app/google-services.json | base64
      
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/fitnessapp/fitnessapp/app/google-services.json
        
    - name: Run Unit tests
      run: ./gradlew test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create file
      run: cat /home/runner/work/fitnessapp/fitnessapp/app/google-services.json | base64
      
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/fitnessapp/fitnessapp/app/google-services.json
      
    - name: Build with Gradle
      run: ./gradlew build
      
  build-project:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run JUnit Tests
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create file
      run: cat /home/runner/work/fitnessapp/fitnessapp/app/google-services.json | base64
      
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/fitnessapp/fitnessapp/app/google-services.json
        
    - name: Build Project
      run: ./gradlew assemble
      
  apk:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run JUnit Tests
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create file
      run: cat /home/runner/work/fitnessapp/fitnessapp/app/google-services.json | base64
      
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0

    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/fitnessapp/fitnessapp/app/google-services.json
        
    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk 
      
      
